---
openapi: 3.0.0
info:
  title: OLDAP-API
  description: RESTful API for oldap
  version: 0.1.0
servers:
- url: http://127.0.0.1:5000
  description: local server...
paths:
  /admin/login:
    post:
      summary: Perform login
      description: Perform login with userid/password. Returns a JWT token.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/admin_login_body'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login_response_200'
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login_response_401'
    delete:
      summary: "Logout"
      description: "Logout from system"
      security:
        - AccessToken: []
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
  /admin/user/{userid}:
    get:
      summary: "Get user info"
      description: "Get all information about a user"
      security:
        - AccessToken: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  userid:
                    type: string
                  lastname:
                    type: string
                  firstname:
                    type: string
                  in_project:
                    type: string
        "401":
          description: Unauthorized"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/login_response_401'
        "404":
          description: "Not Found"
    put:
      summary: "Create a new user"
      description: "Create a new user with the given data"
      security:
        - AccessToken: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
            maxLength: 32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new_user'
      responses:
        "200":
          description: "OK"
    post:
      summary: "Modify a user"
      description: "Modify value(s) of a user definition."
      security:
        - AccessToken: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mod_user'
      responses:
        "200":
          description: "OK"

components:
  schemas:
    admin_login_body:
      type: object
      properties:
        userid:
          type: string
        password:
          type: string
    login_response_200:
      type: object
      properties:
        token:
          type: string
    login_response_401:
      type: object
      properties:
        message:
          type: string
    new_user:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        password:
          type: string
          minLength: 8
    mod_user:
      type: object
      properties:
        firstname:
          type:
            string
        lastname:
          type: string
        password:
          type:
            string
        in_project:
          type:
            array
          items:
            type: object
            properties:
              project_id:
                type:
                  string
              right:
                type:
                  string
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT


