---
openapi: 3.0.0
info:
  title: OLDAP-API
  description: RESTful API for oldap
  version: 0.1.0
servers:
- url: http://127.0.0.1:5000
  description: local server...
paths:
  /admin/auth:
    post:
      summary: Authentification/login
      description: Perform login/logout with userid/password. Returns a JWT token.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/admin_auth_body'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_response_200'
        400:
          description: "Invalid content type"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/auth_response_400'
        "401":
          description: "Unauthorized"
        500:
          description: "Internal Server error"
    delete:
      summary: "Logout"
      description: "Logout from system"
      security:
        - AccessToken: []
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        500:
          description: "Internal Server error"
  /admin/user/{userid}:
    get:
      summary: "Get user info"
      description: "Get all information about a user"
      security:
        - AccessToken: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user_get_body_200'
        "401":
          description: "Unauthorized"
        "404":
          description: "Not Found"
        500:
          description: "Internal Server error"
    put:
      summary: "Create a new user"
      description: "Create a new user with the given data"
      security:
        - AccessToken: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
            maxLength: 32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new_user'
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  useriri:
                    type: string
        400:
          description: "Feldrequirement fehlt"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
        409:
          description: "Userid or useriri already exists"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
        422:
          description: "Passwort zu insicher - wird daher nicht bearbeitet"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
        500:
          description: "Internal Server error"
    post:
      summary: "Modify a user"
      description: "Modify value(s) of a user definition."
      security:
        - AccessToken: []
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mod_user'
        required: true
      responses:
        "200":
          description: "OK"
        400:
          description: "Form/Inhalt der übermittelten Daten stimmt nicht"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
        404:
          description: "Userid not found"
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
        500:
          description: "Internal Server error"

components:
  schemas:
    user_get_body_200:
      type: object
      properties:
        useriri:
          type: string
        userid:
          type: string
        lastname:
          type: string
        firstname:
          type: string
        in_projects:
          type: array
          items:
            type: object
            properties:
              project:
                type: string
              rights:
                type: string
        in_groups:
          type: array
          items:
            type: object
            properties:
              group:
                type: string
              rights:
                type: string
    admin_auth_body:
      type: object
      properties:
        userid:
          type: string
        password:
          type: string
      required:
        - userid
        - password
    auth_response_200:
      type: object
      properties:
        token:
          type: string
    auth_response_400:
      description: if no JSON is sent
      type: object
      properties:
        message:
          type: string
    new_user:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        password:
          type: string
          minLength: 8
        useriri:
          type: string
        in_projects:
          type: array
          items:
            type: object
            properties:
              project:
                type: string
              rights:
                type: string
        in_groups:
          type: array
          items:
            type: object
            properties:
              group:
                type: string
              rights:
                type: string
      required:
        - firstname
        - lastname
        - password

    mod_user:
      type: object
      properties:
        firstname:
          type:
            string
        lastname:
          type: string
        password:
          type:
            string
        in_project:
          type:
            array
          items:
            type: object
            properties:
              project_id:
                type:
                  string
              right:
                type:
                  string
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT


